Interp
sofiachiarenza/Blast.jl pull request #26
Opened 2024-11-19 20:23 UTC by sofiachiarenza

2024-11-25 20:25 UTC, marcobonici commented on README.md
Please, add a bit more info.
1. What the code is supposed to do.
2. How the code work (a small snippet).
3. Authors and everything.

REgarding point 2, it does not have to be self consistent: you might feed some `Pk` and `windows` even without showing how to evaluate them.
You can get insptied by `Capse` repo or chatgpt.

2024-11-25 20:31 UTC, marcobonici commented on src/chebcoefs.jl
> +In practice, the `vals` array is often the power spectrum P(k,χ): the specified axis should contain the wavenumbers `k`. So if the power spectrum is given in a matrix of shape (nk, nχ), axis should b
I am confused. The chosen axis should depend only  on which axis you want to perform the FFT on, right? Sometimes it is the axis related to `z`, sometimes the axis realted to `chi`. Right?

2024-11-25 20:33 UTC, marcobonici commented on src/chebcoefs.jl
> +    correlated_power_spectrum(pk::AbstractArray{T,3}) where T
I don't like the name. Why correlated? I would call it the "unequal_time_power_spectrum" or something similar...but I am open to discussing it :)

2024-11-25 20:33 UTC, marcobonici requested changes
Hi @sofiachiarenza , I gave some comments. Mostly minor stuff.

2024-11-26 04:02 UTC, sofiachiarenza commented
> Hi @sofiachiarenza , I gave some comments. Mostly minor stuff.

Done! ;)

2024-11-26 04:06 UTC, marcobonici commented
Can you just update, in the Readme, the couple of places without the Unicode characters?

\Tilde{T}^{AB}_\ell(\chi_1,\chi_2), for instance.

2024-11-28 20:11 UTC, marcobonici approved these changes

2024-11-28 21:02 UTC, merged